var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/cv-service/export/route.js")
R.c("server/chunks/[root-of-the-server]__0upj~.k._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/_0p6-xjp._.js")
R.c("server/chunks/node_modules_pako_0gctttk._.js")
R.c("server/chunks/_0bc78jt._.js")
R.c("server/chunks/node_modules_xlsx_xlsx_mjs_0eepc5h._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_cv-service_export_route_actions_0018ekb.js")
R.m(43690)
module.exports=R.m(43690).exports
