import { inviteUser } from "@/lib/database";
import { assertAdminPlanCapacity } from "@/lib/saas";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { APP_ROLES, normalizeRole, roleCanAccessModule, type AppRole, type AuthUserProfile } from "@/lib/auth";
import { getAppEnvironment, getAuthCallbackUrl, getStorageBucketNames } from "@/lib/supabase/env";

type RequestContext = {
  supabase: Awaited<ReturnType<typeof createSupabaseServerClient>>;
  admin: ReturnType<typeof createSupabaseAdminClient>;
  profile: AuthUserProfile;
};

type AdminRole = "Super Admin" | "HR Admin" | "Payroll Admin" | "Finance Officer" | "Auditor";
const ADMIN_ROLES: AdminRole[] = ["Super Admin", "HR Admin", "Payroll Admin", "Finance Officer", "Auditor"];
const ADMIN_MANAGE_ROLES: AppRole[] = ["Super Admin", "HR Admin", "Payroll Admin", "Manager"];

const ADMIN_MODULES = [
  "dashboard",
  "people",
  "payroll",
  "leave",
  "recruitment",
  "performance",
  "training",
  "assets",
  "ess",
  "reports",
  "settings",
  "audit",
  "integrations",
  "consultancy",
  "administration",
] as const;

const PERMISSION_SCOPE_BY_ROLE: Record<string, string> = {
  "Super Admin": "global",
  "HR Admin": "company-wide",
  "Payroll Admin": "company-wide",
  "Finance Officer": "company-wide",
  "Manager": "team-only",
  "Recruiter": "department-specific",
  "Employee": "self-only",
  "Auditor": "company-wide",
  "Operator": "branch-specific",
  "Supervisor": "team-only",
};

function safeString(value: unknown, fallback = "") {
  return typeof value === "string" ? value : fallback;
}

function safeNumber(value: unknown, fallback = 0) {
  if (typeof value === "number") {
    return value;
  }

  if (typeof value === "string" && value.length > 0) {
    const parsed = Number(value);
    return Number.isNaN(parsed) ? fallback : parsed;
  }

  return fallback;
}

function asRecord(value: unknown): Record<string, unknown> | null {
  if (Array.isArray(value)) {
    const [first] = value;
    return first && typeof first === "object" ? (first as Record<string, unknown>) : null;
  }

  if (value && typeof value === "object") {
    return value as Record<string, unknown>;
  }

  return null;
}

function toTitle(value: string) {
  return value
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildLogoMark(displayName: string, identifier?: string | null) {
  const seed = safeString(identifier) || displayName;
  const words = seed
    .split(/[\s-]+/)
    .map((part) => part.trim())
    .filter(Boolean);
  const mark = (words.slice(0, 2).map((part) => part.charAt(0)).join("") || seed.slice(0, 2) || "S")
    .toUpperCase();
  return mark.slice(0, 2);
}

const DEFAULT_SOLVA_REPORT_FOOTER = "Generated by Solva HR - www.solvahr.co.ke";
const DEFAULT_POWERED_BY_LABEL = "Powered by Solva HR";

function normaliseBranding(
  rawBranding: Record<string, unknown> | null,
  company: Record<string, unknown> | null
) {
  const companyName = safeString(company?.name, "Solva HR Workspace");
  const employerIdentifier =
    safeString(rawBranding?.employerIdentifier) || safeString(company?.slug).toUpperCase() || "SOLVA";
  const displayName = safeString(rawBranding?.displayName, companyName);

  return {
    displayName,
    employerIdentifier,
    logoPath: safeString(rawBranding?.logoPath),
    logoUrl: safeString(rawBranding?.logoUrl),
    logoMark: safeString(rawBranding?.logoMark, buildLogoMark(displayName, employerIdentifier)),
    reportFooter: safeString(rawBranding?.reportFooter, DEFAULT_SOLVA_REPORT_FOOTER),
    accentColor: safeString(rawBranding?.accentColor, "#1d4ed8"),
    secondaryColor: safeString(rawBranding?.secondaryColor, "#0f172a"),
    companyShortName: safeString(rawBranding?.companyShortName, displayName),
    welcomeMessage: safeString(
      rawBranding?.welcomeMessage,
      `${displayName} HR platform, ${safeString(rawBranding?.poweredByLabel, DEFAULT_POWERED_BY_LABEL).toLowerCase()}.`
    ),
    emailSignature: safeString(
      rawBranding?.emailSignature,
      `${displayName}\n${DEFAULT_POWERED_BY_LABEL}\nwww.solvahr.co.ke`
    ),
    poweredByLabel: safeString(rawBranding?.poweredByLabel, DEFAULT_POWERED_BY_LABEL),
  };
}

async function createBrandingLogoUrl(branding: {
  logoPath?: string;
  logoUrl?: string;
}) {
  if (branding.logoUrl) {
    return branding.logoUrl;
  }

  if (!branding.logoPath) {
    return "";
  }

  const admin = createSupabaseAdminClient();
  const bucket = getStorageBucketNames().payrollDocuments;
  const signed = await admin.storage.from(bucket).createSignedUrl(branding.logoPath, 60 * 60 * 24 * 7);
  if (signed.error || !signed.data?.signedUrl) {
    return "";
  }
  return signed.data.signedUrl;
}

function generateTemporaryPassword() {
  return `Solva!${Math.random().toString(36).slice(2, 8)}A9`;
}

async function getRequestContext(): Promise<RequestContext> {
  const supabase = await createSupabaseServerClient();
  const admin = createSupabaseAdminClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    throw new Error("unauthorized");
  }

  const { data } = await admin
    .from("users")
    .select("id, company_id, full_name, email, phone, role, employee_id, branch_id, department_id, last_login, status")
    .eq("id", user.id)
    .single();

  const profile: AuthUserProfile = data
    ? {
        ...data,
        role: normalizeRole(safeString(data.role)),
      }
    : {
        id: user.id,
        company_id: null,
        full_name: safeString(user.user_metadata.full_name, user.email ?? "Solva User"),
        email: user.email ?? "",
        phone: null,
        role: normalizeRole(safeString(user.app_metadata.role, "Employee")),
        employee_id: null,
        branch_id: null,
        department_id: null,
        last_login: null,
        status: "active",
      };

  if (["suspended", "deactivated", "revoked"].includes(profile.status.toLowerCase())) {
    throw new Error("forbidden");
  }

  return { supabase, admin, profile };
}

function ensureAdminAccess(profile: AuthUserProfile) {
  if (!ADMIN_ROLES.includes(profile.role as AdminRole)) {
    throw new Error("forbidden");
  }
}

function ensureAdminManageAccess(profile: AuthUserProfile) {
  if (!ADMIN_MANAGE_ROLES.includes(profile.role)) {
    throw new Error("forbidden");
  }
}

async function createAuditLog(
  context: RequestContext,
  input: {
    moduleKey: string;
    entityType: string;
    entityId?: string | null;
    action: string;
    beforeValue?: Record<string, unknown> | null;
    afterValue?: Record<string, unknown> | null;
    approvalAction?: string | null;
  }
) {
  await context.admin.from("audit_logs").insert({
    company_id: context.profile.company_id,
    module_key: input.moduleKey,
    entity_type: input.entityType,
    entity_id: input.entityId ?? null,
    action: input.action,
    actor_id: context.profile.id,
    actor_email: context.profile.email,
    actor_role: context.profile.role,
    before_value: input.beforeValue ?? {},
    after_value: input.afterValue ?? {},
    approval_action: input.approvalAction ?? null,
  });
}

export async function recordAccessLogEntry(input: {
  companyId?: string | null;
  userId?: string | null;
  userEmail?: string | null;
  userRole?: string | null;
  moduleKey: string;
  action: string;
  recordType?: string | null;
  recordId?: string | null;
  outcome?: string;
  details?: Record<string, unknown>;
  ipAddress?: string | null;
  deviceInfo?: string | null;
}) {
  const admin = createSupabaseAdminClient();
  await admin.from("access_logs").insert({
    company_id: input.companyId ?? null,
    user_id: input.userId ?? null,
    user_email: input.userEmail ?? null,
    user_role: input.userRole ?? null,
    module_key: input.moduleKey,
    action: input.action,
    record_type: input.recordType ?? null,
    record_id: input.recordId ?? null,
    outcome: input.outcome ?? "success",
    details: input.details ?? {},
    ip_address: input.ipAddress ?? null,
    device_info: input.deviceInfo ?? null,
  });
}

export async function recordLoginSession(input: {
  userId?: string | null;
  companyId?: string | null;
  email: string;
  role?: string | null;
  action: "login" | "logout" | "failed_login";
  status?: string;
  active?: boolean;
  deviceInfo?: string | null;
  ipAddress?: string | null;
}) {
  const admin = createSupabaseAdminClient();
  await admin.from("login_sessions").insert({
    company_id: input.companyId ?? null,
    user_id: input.userId ?? null,
    email: input.email,
    role: input.role ?? null,
    action: input.action,
    status: input.status ?? (input.action === "failed_login" ? "failed" : "success"),
    device_info: input.deviceInfo ?? null,
    ip_address: input.ipAddress ?? null,
    active: input.active ?? input.action === "login",
  });
}

async function lookupUserByEmail(email: string) {
  const admin = createSupabaseAdminClient();
  const { data } = await admin
    .from("users")
    .select("id, company_id, email, role")
    .eq("email", email)
    .maybeSingle();

  return data ?? null;
}

export async function recordAuthAttempt(input: {
  email: string;
  outcome: "success" | "failed" | "blocked";
  userId?: string | null;
  companyId?: string | null;
  role?: string | null;
  reason?: string | null;
  deviceInfo?: string | null;
  ipAddress?: string | null;
}) {
  const knownUser = !input.userId && input.email ? await lookupUserByEmail(input.email) : null;
  const userId = input.userId ?? safeString(knownUser?.id, null as never);
  const companyId = input.companyId ?? safeString(knownUser?.company_id, null as never);
  const role = input.role ?? safeString(knownUser?.role);

  await Promise.all([
    recordAccessLogEntry({
      companyId,
      userId,
      userEmail: input.email,
      userRole: role,
      moduleKey: "administration",
      action: input.outcome === "success" ? "login" : "login_attempt",
      recordType: "auth",
      recordId: userId,
      outcome: input.outcome,
      details: {
        reason: input.reason ?? null,
      },
      deviceInfo: input.deviceInfo,
      ipAddress: input.ipAddress,
    }),
    recordLoginSession({
      userId,
      companyId,
      email: input.email,
      role,
      action: input.outcome === "success" ? "login" : "failed_login",
      status: input.outcome,
      active: input.outcome === "success",
      deviceInfo: input.deviceInfo,
      ipAddress: input.ipAddress,
    }),
  ]);
}

async function touchLastLogin(userId: string) {
  const admin = createSupabaseAdminClient();
  await admin.from("users").update({ last_login: new Date().toISOString() }).eq("id", userId);
}

export async function finalizeUserLogin(userId: string, email: string) {
  const admin = createSupabaseAdminClient();
  const { data, error } = await admin
    .from("users")
    .select("id, company_id, email, role, status")
    .eq("id", userId)
    .maybeSingle();

  if (error) {
    throw error;
  }

  const status = safeString(data?.status, "active").toLowerCase();
  if (["suspended", "deactivated", "revoked"].includes(status)) {
    throw new Error("account_blocked");
  }

  await Promise.all([
    touchLastLogin(userId),
    recordAuthAttempt({
      email,
      outcome: "success",
      userId,
      companyId: safeString(data?.company_id, null as never),
      role: safeString(data?.role),
    }),
  ]);

  return {
    id: safeString(data?.id, userId),
    companyId: safeString(data?.company_id, null as never),
    role: safeString(data?.role),
    status: safeString(data?.status, "active"),
  };
}

export async function finalizeUserLogout(userId: string, email: string) {
  const admin = createSupabaseAdminClient();
  const { data } = await admin
    .from("users")
    .select("company_id, role")
    .eq("id", userId)
    .maybeSingle();

  await admin
    .from("login_sessions")
    .update({ active: false, updated_at: new Date().toISOString() })
    .eq("user_id", userId)
    .eq("active", true);

  await Promise.all([
    recordAccessLogEntry({
      companyId: safeString(data?.company_id, null as never),
      userId,
      userEmail: email,
      userRole: safeString(data?.role),
      moduleKey: "administration",
      action: "logout",
      recordType: "auth",
      recordId: userId,
      outcome: "success",
    }),
    recordLoginSession({
      userId,
      companyId: safeString(data?.company_id, null as never),
      email,
      role: safeString(data?.role),
      action: "logout",
      status: "success",
      active: false,
    }),
  ]);
}

async function listCompanyScopedLookup(table: "branches" | "departments" | "designations" | "job_grades" | "payroll_groups", companyId: string | null) {
  const admin = createSupabaseAdminClient();
  let query = admin.from(table).select("*").order("created_at", { ascending: true });
  if (companyId) {
    query = query.eq("company_id", companyId);
  }
  const { data, error } = await query;
  if (error) {
    throw error;
  }
  return data ?? [];
}

export async function getAdminReferenceData() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  const [branches, departments, designations, jobGrades, payrollGroups, employees] = await Promise.all([
    listCompanyScopedLookup("branches", context.profile.company_id),
    listCompanyScopedLookup("departments", context.profile.company_id),
    listCompanyScopedLookup("designations", context.profile.company_id),
    listCompanyScopedLookup("job_grades", context.profile.company_id),
    listCompanyScopedLookup("payroll_groups", context.profile.company_id),
    context.admin
      .from("employees")
      .select("id, employee_number, first_name, last_name, status")
      .eq("company_id", context.profile.company_id)
      .order("first_name", { ascending: true })
      .limit(500),
  ]);

  if (employees.error) {
    throw employees.error;
  }

  return {
    branches: branches.map((row) => ({
      id: safeString(row.id),
      label: safeString(row.name),
      code: safeString(row.code),
      status: safeString(row.status, "active"),
    })),
    departments: departments.map((row) => ({
      id: safeString(row.id),
      label: safeString(row.name),
      code: safeString(row.code),
      status: safeString(row.status, "active"),
    })),
    designations: designations.map((row) => ({
      id: safeString(row.id),
      label: safeString(row.title || row.name),
      code: safeString(row.code),
      status: safeString(row.status, "active"),
    })),
    jobGrades: jobGrades.map((row) => ({
      id: safeString(row.id),
      label: safeString(row.name),
      code: safeString(row.code),
      status: safeString(row.status, "active"),
    })),
    payrollGroups: payrollGroups.map((row) => ({
      id: safeString(row.id),
      label: safeString(row.name),
      code: safeString(row.code),
      status: safeString(row.status, "active"),
    })),
    employees: (employees.data ?? []).map((row) => ({
      id: safeString(row.id),
      label: `${safeString(row.employee_number)} ${safeString(row.first_name)} ${safeString(row.last_name)}`.trim(),
      status: safeString(row.status, "Active"),
    })),
  };
}

export async function getAdministrationDashboard() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  const [usersResult, branchesResult, departmentsResult, pendingInvitesResult, suspendedUsersResult, sessionsResult, importsResult, workflowsResult] =
    await Promise.all([
      context.admin.from("users").select("*", { count: "exact", head: true }).eq("company_id", context.profile.company_id),
      context.admin.from("branches").select("*", { count: "exact", head: true }).eq("company_id", context.profile.company_id),
      context.admin.from("departments").select("*", { count: "exact", head: true }).eq("company_id", context.profile.company_id),
      context.admin.from("users").select("*", { count: "exact", head: true }).eq("company_id", context.profile.company_id).eq("status", "invited"),
      context.admin.from("users").select("*", { count: "exact", head: true }).eq("company_id", context.profile.company_id).in("status", ["suspended", "deactivated"]),
      context.admin.from("login_sessions").select("email, role, action, status, created_at").eq("company_id", context.profile.company_id).order("created_at", { ascending: false }).limit(8),
      context.admin.from("data_import_jobs").select("id, import_type, status, row_count, success_count, failure_count, created_at").eq("company_id", context.profile.company_id).order("created_at", { ascending: false }).limit(6),
      context.admin.from("approval_workflows").select("id, module_key, status").eq("company_id", context.profile.company_id),
    ]);

  const { data: roles } = await context.admin
    .from("users")
    .select("role")
    .eq("company_id", context.profile.company_id);

  const roleDistribution = APP_ROLES.map((role) => ({
    role,
    count: (roles ?? []).filter((item) => safeString(item.role) === role).length,
  }));

  return {
    stats: {
      totalUsers: usersResult.count ?? 0,
      activeUsers: (usersResult.count ?? 0) - (suspendedUsersResult.count ?? 0) - (pendingInvitesResult.count ?? 0),
      pendingInvites: pendingInvitesResult.count ?? 0,
      suspendedUsers: suspendedUsersResult.count ?? 0,
      branches: branchesResult.count ?? 0,
      departments: departmentsResult.count ?? 0,
      workflows: (workflowsResult.data ?? []).filter((item) => safeString(item.status) === "active").length,
    },
    recentLogins: sessionsResult.data ?? [],
    recentImports: importsResult.data ?? [],
    roleDistribution,
    quickActions: [
      "Invite user",
      "Review permissions",
      "Manage branches",
      "Check system health",
    ],
  };
}

export async function listAdminUsers(filters?: {
  role?: string | null;
  status?: string | null;
  branchId?: string | null;
  departmentId?: string | null;
  linkage?: "linked" | "standalone" | null;
  search?: string | null;
}) {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  let query = context.admin
    .from("users")
    .select(
      "id, full_name, email, phone, role, status, employee_id, branch_id, department_id, last_login, created_at, invited_at, invited_by, activation_state, invited_by_user:invited_by(full_name, email), employee:employee_id(employee_number, first_name, last_name), branch:branch_id(name), department:department_id(name)"
    )
    .eq("company_id", context.profile.company_id)
    .order("created_at", { ascending: false });

  if (filters?.role) {
    query = query.eq("role", filters.role);
  }
  if (filters?.status) {
    query = query.eq("status", filters.status);
  }
  if (filters?.branchId) {
    query = query.eq("branch_id", filters.branchId);
  }
  if (filters?.departmentId) {
    query = query.eq("department_id", filters.departmentId);
  }
  if (filters?.linkage === "linked") {
    query = query.not("employee_id", "is", null);
  }
  if (filters?.linkage === "standalone") {
    query = query.is("employee_id", null);
  }
  if (filters?.search) {
    const search = filters.search.trim();
    query = query.or(`full_name.ilike.%${search}%,email.ilike.%${search}%`);
  }

  const { data, error } = await query.limit(250);
  if (error) {
    throw error;
  }

  return (data ?? []).map((row) => {
    const employee = asRecord(row.employee);
    const invitedBy = asRecord(row.invited_by_user);
    return {
      id: safeString(row.id),
      fullName: safeString(row.full_name),
      email: safeString(row.email),
      phone: safeString(row.phone, "-"),
      role: safeString(row.role),
      status: safeString(row.status),
      linkedEmployee: employee
        ? `${safeString(employee.employee_number)} ${safeString(employee.first_name)} ${safeString(employee.last_name)}`.trim()
        : "Standalone user",
      linkedEmployeeId: safeString(row.employee_id),
      branch: safeString(asRecord(row.branch)?.name, "Unassigned"),
      branchId: safeString(row.branch_id),
      department: safeString(asRecord(row.department)?.name, "Unassigned"),
      departmentId: safeString(row.department_id),
      lastLogin: safeString(row.last_login, "Never"),
      createdAt: safeString(row.created_at),
      invitedAt: safeString(row.invited_at, "-"),
      invitedBy: invitedBy ? `${safeString(invitedBy.full_name)} (${safeString(invitedBy.email)})` : "-",
      activationState: safeString(row.activation_state, safeString(row.status)),
    };
  });
}

export async function getAdminUserDetail(userId: string) {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  const [userResult, sessionsResult, auditResult, approvalsResult] = await Promise.all([
    context.admin
      .from("users")
      .select(
        "id, full_name, email, phone, role, status, employee_id, branch_id, department_id, last_login, created_at, invited_at, activated_at, suspended_at, deactivated_at, activation_state, must_reset_password, employee:employee_id(employee_number, first_name, last_name), branch:branch_id(name), department:department_id(name)"
      )
      .eq("company_id", context.profile.company_id)
      .eq("id", userId)
      .maybeSingle(),
    context.admin
      .from("login_sessions")
      .select("id, action, status, email, role, device_info, ip_address, created_at, active")
      .eq("user_id", userId)
      .order("created_at", { ascending: false })
      .limit(10),
    context.admin
      .from("audit_logs")
      .select("id, module_key, action, approval_action, created_at, before_value, after_value")
      .eq("actor_id", userId)
      .order("created_at", { ascending: false })
      .limit(10),
    context.admin
      .from("approval_tasks")
      .select("id, title, status, stage, updated_at, module_key")
      .or(`requested_by.eq.${userId}`)
      .order("updated_at", { ascending: false })
      .limit(10),
  ]);

  if (userResult.error || !userResult.data) {
    throw userResult.error ?? new Error("user_not_found");
  }

  const user = userResult.data;
  const employee = asRecord(user.employee);
  const branch = asRecord(user.branch);
  const department = asRecord(user.department);

  return {
    id: safeString(user.id),
    fullName: safeString(user.full_name),
    email: safeString(user.email),
    phone: safeString(user.phone, "-"),
    role: safeString(user.role),
    status: safeString(user.status),
    linkedEmployee: employee
      ? {
          id: safeString(user.employee_id),
          label: `${safeString(employee.employee_number)} ${safeString(employee.first_name)} ${safeString(employee.last_name)}`.trim(),
        }
      : null,
    branch: branch ? { id: safeString(user.branch_id), name: safeString(branch.name) } : null,
    department: department ? { id: safeString(user.department_id), name: safeString(department.name) } : null,
    lastLogin: safeString(user.last_login, "Never"),
    createdAt: safeString(user.created_at),
    invitedAt: safeString(user.invited_at, "-"),
    activatedAt: safeString(user.activated_at, "-"),
    suspendedAt: safeString(user.suspended_at, "-"),
    deactivatedAt: safeString(user.deactivated_at, "-"),
    activationState: safeString(user.activation_state, safeString(user.status)),
    mustResetPassword: Boolean(user.must_reset_password),
    permissionsSummary: {
      modules: ADMIN_MODULES.filter((moduleKey) => roleCanAccessModule(normalizeRole(safeString(user.role)), moduleKey)).length,
      scope: PERMISSION_SCOPE_BY_ROLE[safeString(user.role)] ?? "company-wide",
    },
    loginHistory: sessionsResult.data ?? [],
    recentAudit: auditResult.data ?? [],
    recentApprovals: approvalsResult.data ?? [],
  };
}

export async function createAdminUser(input: {
  fullName: string;
  email: string;
  phone?: string | null;
  role: AppRole;
  employeeId?: string | null;
  branchId?: string | null;
  departmentId?: string | null;
  inviteOnly?: boolean;
  temporaryPassword?: string | null;
}) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);
  await assertAdminPlanCapacity(context.profile.company_id);

  if (input.inviteOnly) {
    const invite = await inviteUser({
      email: input.email,
      fullName: input.fullName,
      role: input.role,
      employeeId: input.employeeId,
      branchId: input.branchId,
      departmentId: input.departmentId,
    });

    const admin = createSupabaseAdminClient();
    await admin
      .from("users")
      .update({
        phone: input.phone ?? null,
        invited_by: context.profile.id,
        invited_at: new Date().toISOString(),
        activation_state: "invited",
        must_reset_password: true,
      })
      .eq("id", invite.id);

    return {
      ...invite,
      inviteOnly: true,
    };
  }

  const temporaryPassword = input.temporaryPassword?.trim() || generateTemporaryPassword();
  const admin = createSupabaseAdminClient();
  const created = await admin.auth.admin.createUser({
    email: input.email,
    password: temporaryPassword,
    email_confirm: true,
    user_metadata: {
      full_name: input.fullName,
      phone: input.phone ?? null,
    },
    app_metadata: {
      role: input.role,
    },
  });

  if (created.error || !created.data.user) {
    throw created.error ?? new Error("user_create_failed");
  }

  const { data, error } = await admin
    .from("users")
    .upsert({
      id: created.data.user.id,
      company_id: context.profile.company_id,
      full_name: input.fullName,
      email: input.email,
      phone: input.phone ?? null,
      role: input.role,
      employee_id: input.employeeId ?? null,
      branch_id: input.branchId ?? null,
      department_id: input.departmentId ?? null,
      status: "active",
      activation_state: "active",
      invited_by: context.profile.id,
      invited_at: new Date().toISOString(),
      activated_at: new Date().toISOString(),
      must_reset_password: true,
    })
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("user_profile_upsert_failed");
  }

  await Promise.all([
    createAuditLog(context, {
      moduleKey: "administration",
      entityType: "user",
      entityId: safeString(data.id),
      action: "created_user_account",
      afterValue: data as Record<string, unknown>,
    }),
    recordAccessLogEntry({
      companyId: context.profile.company_id,
      userId: context.profile.id,
      userEmail: context.profile.email,
      userRole: context.profile.role,
      moduleKey: "administration",
      action: "create_user",
      recordType: "user",
      recordId: safeString(data.id),
      outcome: "success",
      details: { assignedRole: input.role },
    }),
  ]);

  return {
    id: safeString(data.id),
    email: input.email,
    role: input.role,
    temporaryPassword,
  };
}

function ensureAssignableRole(profile: AuthUserProfile, role: AppRole) {
  if (profile.role === "Super Admin") {
    return;
  }

  const allowedRoles: AppRole[] = ["Employee", "Manager", "Recruiter", "Supervisor", "Operator"];
  if (!allowedRoles.includes(role)) {
    throw new Error("forbidden");
  }
}

export async function createEmployeeLinkedUserAccounts(input: {
  employeeIds: string[];
  role?: AppRole;
}) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);

  const targetRole = normalizeRole(safeString(input.role, "Employee"));
  ensureAssignableRole(context.profile, targetRole);

  const employeeIds = Array.from(new Set(input.employeeIds.filter(Boolean)));
  if (!employeeIds.length) {
    throw new Error("employee_selection_required");
  }

  const employeeResult = await context.admin
    .from("employees")
    .select(
      "id, employee_number, first_name, last_name, email, phone, branch_id, department_id, linked_user:users!users_employee_id_fkey(id, email, role, status)"
    )
    .eq("company_id", context.profile.company_id)
    .in("id", employeeIds);

  if (employeeResult.error) {
    throw employeeResult.error;
  }

  const created: Array<{
    employeeId: string;
    email: string;
    role: string;
    userId: string | null;
    temporaryPassword?: string | null;
  }> = [];
  const skipped: Array<{ employeeId: string; employeeName: string; reason: string }> = [];
  const failed: Array<{ employeeId: string; employeeName: string; reason: string }> = [];

  for (const row of employeeResult.data ?? []) {
    const employee = row as Record<string, unknown>;
    const employeeId = safeString(employee.id);
    const employeeName = `${safeString(employee.first_name)} ${safeString(employee.last_name)}`.trim();
    const linkedUser = asRecord(employee.linked_user);
    const email = safeString(employee.email).trim().toLowerCase();

    if (linkedUser?.id) {
      skipped.push({ employeeId, employeeName, reason: "User account already exists." });
      continue;
    }

    if (!email || !email.includes("@")) {
      skipped.push({ employeeId, employeeName, reason: "Employee does not have a valid email address." });
      continue;
    }

    try {
      const result = await createAdminUser({
        fullName: employeeName,
        email,
        phone: safeString(employee.phone) || null,
        role: targetRole,
        employeeId,
        branchId: safeString(employee.branch_id) || null,
        departmentId: safeString(employee.department_id) || null,
        inviteOnly: false,
        temporaryPassword: "RobotCafe123",
      });

      created.push({
        employeeId,
        email,
        role: targetRole,
        userId: safeString(result.id) || null,
        temporaryPassword: safeString((result as Record<string, unknown>).temporaryPassword) || null,
      });
    } catch (error) {
      failed.push({
        employeeId,
        employeeName,
        reason: error instanceof Error ? error.message : "Could not create the user account.",
      });
    }
  }

  return {
    role: targetRole,
    created,
    skipped,
    failed,
    summary: {
      requested: employeeIds.length,
      created: created.length,
      skipped: skipped.length,
      failed: failed.length,
    },
  };
}

export async function updateAdminUser(
  userId: string,
  input: {
    fullName?: string;
    phone?: string | null;
    role?: AppRole;
    employeeId?: string | null;
    branchId?: string | null;
    departmentId?: string | null;
  }
) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);

  const admin = createSupabaseAdminClient();
  const before = await admin.from("users").select("*").eq("id", userId).single();
  if (before.error || !before.data) {
    throw before.error ?? new Error("user_not_found");
  }

  const { data, error } = await admin
    .from("users")
    .update({
      ...(typeof input.fullName !== "undefined" ? { full_name: input.fullName } : {}),
      ...(typeof input.phone !== "undefined" ? { phone: input.phone } : {}),
      ...(typeof input.role !== "undefined" ? { role: input.role } : {}),
      ...(typeof input.employeeId !== "undefined" ? { employee_id: input.employeeId } : {}),
      ...(typeof input.branchId !== "undefined" ? { branch_id: input.branchId } : {}),
      ...(typeof input.departmentId !== "undefined" ? { department_id: input.departmentId } : {}),
    })
    .eq("id", userId)
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("user_update_failed");
  }

  await admin.auth.admin.updateUserById(userId, {
    ...(typeof input.fullName !== "undefined" ? { user_metadata: { ...(before.data.user_metadata ?? {}), full_name: input.fullName } } : {}),
    ...(typeof input.role !== "undefined" ? { app_metadata: { role: input.role } } : {}),
  });

  await Promise.all([
    createAuditLog(context, {
      moduleKey: "administration",
      entityType: "user",
      entityId: userId,
      action: "updated_user_account",
      beforeValue: before.data as Record<string, unknown>,
      afterValue: data as Record<string, unknown>,
    }),
    recordAccessLogEntry({
      companyId: context.profile.company_id,
      userId: context.profile.id,
      userEmail: context.profile.email,
      userRole: context.profile.role,
      moduleKey: "administration",
      action: "update_user",
      recordType: "user",
      recordId: userId,
      outcome: "success",
    }),
  ]);

  return data;
}

export async function runAdminUserAction(
  userId: string,
  action:
    | "activate"
    | "suspend"
    | "deactivate"
    | "reactivate"
    | "resend_invite"
    | "reset_password"
    | "set_temporary_password"
    | "revoke_invite"
    | "force_sign_out",
  options?: {
    temporaryPassword?: string | null;
  }
) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);

  const admin = createSupabaseAdminClient();
  const before = await admin.from("users").select("*").eq("id", userId).single();
  if (before.error || !before.data) {
    throw before.error ?? new Error("user_not_found");
  }

  const user = before.data;
  const timestamp = new Date().toISOString();

  if (action === "resend_invite" || action === "reset_password") {
    const response = await admin.auth.resetPasswordForEmail(safeString(user.email), {
      redirectTo: getAuthCallbackUrl("/reset-password"),
    });

    if (response.error) {
      throw response.error;
    }
  }

  if (action === "force_sign_out") {
    await admin
      .from("login_sessions")
      .update({ active: false, updated_at: timestamp })
      .eq("user_id", userId)
      .eq("active", true);
  }

  let patch: Record<string, unknown> = {};
  let updated = user;
  if (action === "activate" || action === "reactivate") {
    const authUpdate = await admin.auth.admin.updateUserById(userId, {
      email_confirm: true,
    });

    if (authUpdate.error) {
      throw authUpdate.error;
    }

    patch = {
      status: "active",
      activation_state: "active",
      activated_at: timestamp,
      suspended_at: null,
      deactivated_at: null,
    };
  } else if (action === "suspend") {
    patch = {
      status: "suspended",
      activation_state: "suspended",
      suspended_at: timestamp,
    };
  } else if (action === "deactivate") {
    patch = {
      status: "deactivated",
      activation_state: "deactivated",
      deactivated_at: timestamp,
    };
  } else if (action === "revoke_invite") {
    patch = {
      status: "revoked",
      activation_state: "revoked",
      deactivated_at: timestamp,
    };
  } else if (action === "resend_invite") {
    patch = {
      status: "invited",
      activation_state: "invited",
      invited_at: timestamp,
      must_reset_password: true,
    };
  } else if (action === "reset_password") {
    patch = {
      must_reset_password: true,
    };
  } else if (action === "set_temporary_password") {
    const temporaryPassword = options?.temporaryPassword?.trim() || generateTemporaryPassword();
    const passwordUpdate = await admin.auth.admin.updateUserById(userId, {
      password: temporaryPassword,
      email_confirm: true,
    });

    if (passwordUpdate.error) {
      throw passwordUpdate.error;
    }

    patch = {
      must_reset_password: true,
    };

    const response = await admin.from("users").update(patch).eq("id", userId).select("*").single();
    if (response.error || !response.data) {
      throw response.error ?? new Error("user_action_failed");
    }
    updated = response.data;

    await Promise.all([
      createAuditLog(context, {
        moduleKey: "administration",
        entityType: "user",
        entityId: userId,
        action: "set_temporary_password",
        beforeValue: before.data as Record<string, unknown>,
        afterValue: {
          ...(updated as Record<string, unknown>),
          temporaryPasswordIssuedAt: timestamp,
        },
      }),
      recordAccessLogEntry({
        companyId: context.profile.company_id,
        userId: context.profile.id,
        userEmail: context.profile.email,
        userRole: context.profile.role,
        moduleKey: "administration",
        action: "set_temporary_password",
        recordType: "user",
        recordId: userId,
        outcome: "success",
      }),
    ]);

    return {
      id: safeString(updated.id),
      status: safeString(updated.status),
      activationState: safeString(updated.activation_state),
      action,
      temporaryPassword,
    };
  }

  if (Object.keys(patch).length > 0) {
    const response = await admin.from("users").update(patch).eq("id", userId).select("*").single();
    if (response.error || !response.data) {
      throw response.error ?? new Error("user_action_failed");
    }
    updated = response.data;
  }

  await Promise.all([
    createAuditLog(context, {
      moduleKey: "administration",
      entityType: "user",
      entityId: userId,
      action: `${action}_user_account`,
      beforeValue: before.data as Record<string, unknown>,
      afterValue: updated as Record<string, unknown>,
    }),
    recordAccessLogEntry({
      companyId: context.profile.company_id,
      userId: context.profile.id,
      userEmail: context.profile.email,
      userRole: context.profile.role,
      moduleKey: "administration",
      action,
      recordType: "user",
      recordId: userId,
      outcome: "success",
    }),
  ]);

  return {
    id: safeString(updated.id),
    status: safeString(updated.status),
    activationState: safeString(updated.activation_state),
    action,
  };
}

export async function listRoleDefinitions() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  const [rolesResult, usersResult, permissionsResult] = await Promise.all([
    context.admin
      .from("role_definitions")
      .select("*")
      .eq("company_id", context.profile.company_id)
      .order("name", { ascending: true }),
    context.admin
      .from("users")
      .select("role")
      .eq("company_id", context.profile.company_id),
    context.admin
      .from("role_permissions")
      .select("role_key, module_key, can_view")
      .eq("company_id", context.profile.company_id),
  ]);

  if (rolesResult.error || usersResult.error || permissionsResult.error) {
    throw rolesResult.error ?? usersResult.error ?? permissionsResult.error ?? new Error("role_query_failed");
  }

  return (rolesResult.data ?? []).map((role) => ({
    id: safeString(role.id),
    roleKey: safeString(role.role_key),
    name: safeString(role.name),
    description: safeString(role.description),
    scopeType: safeString(role.scope_type),
    status: safeString(role.status),
    isSystem: Boolean(role.is_system),
    assignable: Boolean(role.assignable),
    userCount: (usersResult.data ?? []).filter((user) => safeString(user.role) === safeString(role.role_key)).length,
    modules: (permissionsResult.data ?? [])
      .filter((permission) => safeString(permission.role_key) === safeString(role.role_key) && Boolean(permission.can_view))
      .map((permission) => safeString(permission.module_key)),
  }));
}

export async function createRoleDefinition(input: {
  roleKey: string;
  name: string;
  description?: string | null;
  scopeType?: string | null;
  assignable?: boolean;
}) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);

  const normalizedKey = input.roleKey.trim();
  const assignable = Boolean(input.assignable && APP_ROLES.includes(normalizedKey as AppRole));
  const { data, error } = await context.admin
    .from("role_definitions")
    .insert({
      company_id: context.profile.company_id,
      role_key: normalizedKey,
      name: input.name,
      description: input.description ?? null,
      scope_type: input.scopeType ?? "company-wide",
      is_system: false,
      assignable,
      status: "inactive",
    })
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("role_create_failed");
  }

  await createAuditLog(context, {
    moduleKey: "administration",
    entityType: "role_definition",
    entityId: safeString(data.id),
    action: "created_role_definition",
    afterValue: data as Record<string, unknown>,
  });

  return data;
}

export async function updateRoleDefinition(roleKey: string, patch: Record<string, unknown>) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);

  const before = await context.admin
    .from("role_definitions")
    .select("*")
    .eq("company_id", context.profile.company_id)
    .eq("role_key", roleKey)
    .single();

  if (before.error || !before.data) {
    throw before.error ?? new Error("role_not_found");
  }

  const { data, error } = await context.admin
    .from("role_definitions")
    .update(patch)
    .eq("company_id", context.profile.company_id)
    .eq("role_key", roleKey)
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("role_update_failed");
  }

  await createAuditLog(context, {
    moduleKey: "administration",
    entityType: "role_definition",
    entityId: safeString(data.id),
    action: "updated_role_definition",
    beforeValue: before.data as Record<string, unknown>,
    afterValue: data as Record<string, unknown>,
  });

  return data;
}

export async function cloneRoleDefinition(roleKey: string, cloneName: string) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);

  const [roleResult, permissionsResult] = await Promise.all([
    context.admin
      .from("role_definitions")
      .select("*")
      .eq("company_id", context.profile.company_id)
      .eq("role_key", roleKey)
      .single(),
    context.admin
      .from("role_permissions")
      .select("*")
      .eq("company_id", context.profile.company_id)
      .eq("role_key", roleKey),
  ]);

  if (roleResult.error || !roleResult.data) {
    throw roleResult.error ?? new Error("role_not_found");
  }

  const clonedKey = `${cloneName.toLowerCase().replace(/[^a-z0-9]+/g, "_")}_${Date.now().toString().slice(-4)}`;
  const created = await createRoleDefinition({
    roleKey: clonedKey,
    name: cloneName,
    description: `Template cloned from ${roleResult.data.name}.`,
    scopeType: safeString(roleResult.data.scope_type),
    assignable: false,
  });

  const clonedPermissions = (permissionsResult.data ?? []).map((permission) => ({
    company_id: context.profile.company_id,
    role_key: clonedKey,
    module_key: safeString(permission.module_key),
    scope_type: safeString(permission.scope_type),
    can_view: Boolean(permission.can_view),
    can_create: Boolean(permission.can_create),
    can_edit: Boolean(permission.can_edit),
    can_approve: Boolean(permission.can_approve),
    can_export: Boolean(permission.can_export),
    can_delete: Boolean(permission.can_delete),
    can_admin: Boolean(permission.can_admin),
    status: safeString(permission.status, "active"),
  }));

  if (clonedPermissions.length > 0) {
    await context.admin.from("role_permissions").insert(clonedPermissions);
  }

  return created;
}

export async function listPermissionsMatrix() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  const [rolesResult, permissionsResult] = await Promise.all([
    context.admin
      .from("role_definitions")
      .select("role_key, name, scope_type, status, assignable")
      .eq("company_id", context.profile.company_id)
      .order("name", { ascending: true }),
    context.admin
      .from("role_permissions")
      .select("*")
      .eq("company_id", context.profile.company_id)
      .order("module_key", { ascending: true }),
  ]);

  if (rolesResult.error || permissionsResult.error) {
    throw rolesResult.error ?? permissionsResult.error ?? new Error("permissions_query_failed");
  }

  return {
    roles: rolesResult.data ?? [],
    modules: [...ADMIN_MODULES],
    matrix: permissionsResult.data ?? [],
  };
}

export async function updateRolePermission(
  roleKey: string,
  moduleKey: string,
  patch: {
    scopeType?: string;
    canView?: boolean;
    canCreate?: boolean;
    canEdit?: boolean;
    canApprove?: boolean;
    canExport?: boolean;
    canDelete?: boolean;
    canAdmin?: boolean;
    status?: string;
  }
) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);

  const before = await context.admin
    .from("role_permissions")
    .select("*")
    .eq("company_id", context.profile.company_id)
    .eq("role_key", roleKey)
    .eq("module_key", moduleKey)
    .maybeSingle();

  const payload = {
    company_id: context.profile.company_id,
    role_key: roleKey,
    module_key: moduleKey,
    scope_type: patch.scopeType ?? safeString(before.data?.scope_type, "company-wide"),
    can_view: patch.canView ?? Boolean(before.data?.can_view),
    can_create: patch.canCreate ?? Boolean(before.data?.can_create),
    can_edit: patch.canEdit ?? Boolean(before.data?.can_edit),
    can_approve: patch.canApprove ?? Boolean(before.data?.can_approve),
    can_export: patch.canExport ?? Boolean(before.data?.can_export),
    can_delete: patch.canDelete ?? Boolean(before.data?.can_delete),
    can_admin: patch.canAdmin ?? Boolean(before.data?.can_admin),
    status: patch.status ?? safeString(before.data?.status, "active"),
  };

  const { data, error } = await context.admin
    .from("role_permissions")
    .upsert(payload, { onConflict: "company_id,role_key,module_key" })
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("permission_update_failed");
  }

  await createAuditLog(context, {
    moduleKey: "administration",
    entityType: "role_permission",
    entityId: safeString(data.id),
    action: "updated_role_permission",
    beforeValue: before.data as Record<string, unknown> | null,
    afterValue: data as Record<string, unknown>,
  });

  return data;
}

async function getOrCreateCompanySettings(context: RequestContext) {
  const existing = await context.admin
    .from("company_settings")
    .select("*")
    .eq("company_id", context.profile.company_id)
    .maybeSingle();

  if (existing.data) {
    return existing.data;
  }

  const { data, error } = await context.admin
    .from("company_settings")
    .upsert({ company_id: context.profile.company_id }, { onConflict: "company_id" })
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("company_settings_create_failed");
  }

  return data;
}

export async function getCompanySettings() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  const [companyResult, settings] = await Promise.all([
    context.admin.from("companies").select("*").eq("id", context.profile.company_id).single(),
    getOrCreateCompanySettings(context),
  ]);

  if (companyResult.error || !companyResult.data) {
    throw companyResult.error ?? new Error("company_not_found");
  }

  const branding = normaliseBranding(asRecord((settings as Record<string, unknown> | null)?.branding), companyResult.data as Record<string, unknown>);
  const logoUrl = await createBrandingLogoUrl(branding);

  return {
    ...companyResult.data,
    settings: {
      ...(settings as Record<string, unknown>),
      branding: {
        ...branding,
        logoUrl,
      },
    },
  };
}

export async function getPublicTenantBranding(tenantSlug: string) {
  const slug = slugify(tenantSlug);
  if (!slug) {
    return null;
  }

  const admin = createSupabaseAdminClient();
  const companyResult = await admin.from("companies").select("id, name, slug").eq("slug", slug).maybeSingle();

  const company = asRecord(companyResult.data);
  if (!company) {
    return null;
  }

  const settingsResult = await admin
    .from("company_settings")
    .select("branding")
    .eq("company_id", safeString(company.id))
    .maybeSingle();

  const branding = normaliseBranding(
    asRecord((settingsResult.data as Record<string, unknown> | null)?.branding),
    company
  );
  const logoUrl = await createBrandingLogoUrl(branding);

  return {
    displayName: branding.displayName,
    companyShortName: branding.companyShortName,
    welcomeMessage: branding.welcomeMessage,
    logoUrl,
    logoMark: branding.logoMark,
    accentColor: branding.accentColor,
    secondaryColor: branding.secondaryColor,
    poweredByLabel: branding.poweredByLabel,
  };
}

export async function updateCompanySettings(input: Record<string, unknown>) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);

  const companyPatch: Record<string, unknown> = {};
  if (typeof input.name !== "undefined") {
    const name = safeString(input.name).trim();
    companyPatch.name = name;
    if (name) {
      companyPatch.slug = slugify(name);
    }
  }
  if (typeof input.status !== "undefined") companyPatch.status = input.status;

  if (Object.keys(companyPatch).length > 0) {
    await context.admin.from("companies").update(companyPatch).eq("id", context.profile.company_id);
  }

  const existingSettings = await getOrCreateCompanySettings(context);
  const existingBranding = normaliseBranding(
    asRecord((existingSettings as Record<string, unknown> | null)?.branding),
    companyPatch
  );
  const incomingBranding = asRecord(input.branding);
  const branding = incomingBranding
    ? {
        ...existingBranding,
        ...incomingBranding,
        displayName: safeString(incomingBranding.displayName, existingBranding.displayName),
        employerIdentifier: safeString(
          incomingBranding.employerIdentifier,
          existingBranding.employerIdentifier
        ),
        logoPath: safeString(incomingBranding.logoPath, existingBranding.logoPath),
        logoUrl: safeString(incomingBranding.logoUrl, existingBranding.logoUrl),
        reportFooter: safeString(incomingBranding.reportFooter, existingBranding.reportFooter),
        accentColor: safeString(incomingBranding.accentColor, existingBranding.accentColor),
        secondaryColor: safeString(incomingBranding.secondaryColor, existingBranding.secondaryColor),
        companyShortName: safeString(incomingBranding.companyShortName, existingBranding.companyShortName),
        welcomeMessage: safeString(incomingBranding.welcomeMessage, existingBranding.welcomeMessage),
        emailSignature: safeString(incomingBranding.emailSignature, existingBranding.emailSignature),
        poweredByLabel: safeString(incomingBranding.poweredByLabel, existingBranding.poweredByLabel),
        logoMark: safeString(
          incomingBranding.logoMark,
          buildLogoMark(
            safeString(incomingBranding.displayName, existingBranding.displayName),
            safeString(incomingBranding.employerIdentifier, existingBranding.employerIdentifier)
          )
        ),
      }
    : existingBranding;

  const settingsPatch = {
    company_id: context.profile.company_id,
    ...(typeof input.primary_email !== "undefined" ? { primary_email: input.primary_email } : {}),
    ...(typeof input.phone !== "undefined" ? { phone: input.phone } : {}),
    ...(typeof input.physical_address !== "undefined" ? { physical_address: input.physical_address } : {}),
    ...(typeof input.registration_number !== "undefined" ? { registration_number: input.registration_number } : {}),
    ...(typeof input.tax_pin !== "undefined" ? { tax_pin: input.tax_pin } : {}),
    ...(typeof input.default_currency !== "undefined" ? { default_currency: input.default_currency } : {}),
    ...(typeof input.country !== "undefined" ? { country: input.country } : {}),
    ...(typeof input.timezone !== "undefined" ? { timezone: input.timezone } : {}),
    ...(typeof input.working_days !== "undefined" ? { working_days: input.working_days } : {}),
    ...(typeof input.payroll_defaults !== "undefined" ? { payroll_defaults: input.payroll_defaults } : {}),
    ...(typeof input.leave_year_settings !== "undefined" ? { leave_year_settings: input.leave_year_settings } : {}),
    branding,
  };

  const { data, error } = await context.admin
    .from("company_settings")
    .upsert(settingsPatch, { onConflict: "company_id" })
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("company_settings_update_failed");
  }

  await createAuditLog(context, {
    moduleKey: "administration",
    entityType: "company_settings",
    entityId: context.profile.company_id ?? undefined,
    action: "updated_company_settings",
    afterValue: data as Record<string, unknown>,
  });

  return data;
}

export async function uploadCompanyLogo(input: { file: File }) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);

  if (!context.profile.company_id) {
    throw new Error("missing_company_context");
  }

  const file = input.file;
  if (!file || !file.size) {
    throw new Error("logo_file_missing");
  }

  if (!/^image\/(png|jpeg|jpg|webp|svg\+xml)$/i.test(file.type)) {
    throw new Error("logo_file_type_not_supported");
  }

  const ext = file.name.split(".").pop() ?? "png";
  const bucket = getStorageBucketNames().payrollDocuments;
  const path = `companies/${context.profile.company_id}/branding/logo-${Date.now()}.${ext}`;
  const buffer = Buffer.from(await file.arrayBuffer());

  const uploadResult = await context.admin.storage.from(bucket).upload(path, buffer, {
    contentType: file.type,
    upsert: true,
  });

  if (uploadResult.error) {
    throw uploadResult.error;
  }

  const companyResult = await context.admin
    .from("companies")
    .select("name, slug")
    .eq("id", context.profile.company_id)
    .single();

  if (companyResult.error || !companyResult.data) {
    throw companyResult.error ?? new Error("company_not_found");
  }

  const existingSettings = await getOrCreateCompanySettings(context);
  const existingBranding = normaliseBranding(
    asRecord((existingSettings as Record<string, unknown> | null)?.branding),
    companyResult.data as Record<string, unknown>
  );
  const signedUrl = await createBrandingLogoUrl({ logoPath: path });
  const branding = {
    ...existingBranding,
    logoPath: path,
    logoUrl: signedUrl,
    logoMark: buildLogoMark(existingBranding.displayName, existingBranding.employerIdentifier),
  };

  const { data, error } = await context.admin
    .from("company_settings")
    .upsert(
      {
        company_id: context.profile.company_id,
        branding,
      },
      { onConflict: "company_id" }
    )
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("company_logo_update_failed");
  }

  await createAuditLog(context, {
    moduleKey: "administration",
    entityType: "company_branding",
    entityId: context.profile.company_id,
    action: "uploaded_company_logo",
    afterValue: {
      logoPath: path,
      logoUrl: signedUrl,
    },
  });

  return {
    branding: {
      ...branding,
      logoUrl: signedUrl,
    },
  };
}

export async function listApprovalWorkflowSettings() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  const { data, error } = await context.admin
    .from("approval_workflows")
    .select("*")
    .eq("company_id", context.profile.company_id)
    .order("module_key", { ascending: true });

  if (error) {
    throw error;
  }

  return data ?? [];
}

export async function saveApprovalWorkflow(input: {
  id?: string | null;
  moduleKey: string;
  name: string;
  steps: Array<Record<string, unknown>>;
  moduleScope?: string;
  makerCheckerEnabled?: boolean;
  finalApprovalRequired?: boolean;
  escalationRule?: Record<string, unknown>;
  status?: string;
}) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);

  const payload = {
    company_id: context.profile.company_id,
    module_key: input.moduleKey,
    name: input.name,
    steps: input.steps,
    module_scope: input.moduleScope ?? "company-wide",
    maker_checker_enabled: input.makerCheckerEnabled ?? false,
    final_approval_required: input.finalApprovalRequired ?? true,
    escalation_rule: input.escalationRule ?? {},
    status: input.status ?? "active",
  };

  const query = input.id
    ? context.admin.from("approval_workflows").update(payload).eq("id", input.id)
    : context.admin.from("approval_workflows").insert(payload);

  const { data, error } = await query.select("*").single();
  if (error || !data) {
    throw error ?? new Error("workflow_save_failed");
  }

  await createAuditLog(context, {
    moduleKey: "administration",
    entityType: "approval_workflow",
    entityId: safeString(data.id),
    action: input.id ? "updated_approval_workflow" : "created_approval_workflow",
    afterValue: data as Record<string, unknown>,
  });

  return data;
}

async function getOrCreateSettingRow<T extends "notification_settings" | "security_settings">(
  context: RequestContext,
  table: T
) {
  const existing = await context.admin
    .from(table)
    .select("*")
    .eq("company_id", context.profile.company_id)
    .maybeSingle();

  if (existing.data) {
    return existing.data;
  }

  const { data, error } = await context.admin
    .from(table)
    .upsert({ company_id: context.profile.company_id }, { onConflict: "company_id" })
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error(`${table}_create_failed`);
  }

  return data;
}

export async function getAdminNotificationSettings() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);
  return getOrCreateSettingRow(context, "notification_settings");
}

export async function updateAdminNotificationSettings(input: Record<string, unknown>) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);

  const { data, error } = await context.admin
    .from("notification_settings")
    .upsert(
      {
        company_id: context.profile.company_id,
        ...(typeof input.email_enabled !== "undefined" ? { email_enabled: input.email_enabled } : {}),
        ...(typeof input.in_app_enabled !== "undefined" ? { in_app_enabled: input.in_app_enabled } : {}),
        ...(typeof input.sms_enabled !== "undefined" ? { sms_enabled: input.sms_enabled } : {}),
        ...(typeof input.event_preferences !== "undefined" ? { event_preferences: input.event_preferences } : {}),
        ...(typeof input.reminder_preferences !== "undefined" ? { reminder_preferences: input.reminder_preferences } : {}),
      },
      { onConflict: "company_id" }
    )
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("notification_settings_update_failed");
  }

  await createAuditLog(context, {
    moduleKey: "administration",
    entityType: "notification_settings",
    entityId: context.profile.company_id ?? undefined,
    action: "updated_notification_settings",
    afterValue: data as Record<string, unknown>,
  });

  return data;
}

export async function getSecuritySettings() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);
  return getOrCreateSettingRow(context, "security_settings");
}

export async function updateSecuritySettings(input: Record<string, unknown>) {
  const context = await getRequestContext();
  ensureRole(context.profile, ["Super Admin", "HR Admin"]);

  const { data, error } = await context.admin
    .from("security_settings")
    .upsert(
      {
        company_id: context.profile.company_id,
        ...(typeof input.session_timeout_minutes !== "undefined" ? { session_timeout_minutes: input.session_timeout_minutes } : {}),
        ...(typeof input.password_policy !== "undefined" ? { password_policy: input.password_policy } : {}),
        ...(typeof input.mfa_required !== "undefined" ? { mfa_required: input.mfa_required } : {}),
        ...(typeof input.download_restrictions !== "undefined" ? { download_restrictions: input.download_restrictions } : {}),
        ...(typeof input.document_access !== "undefined" ? { document_access: input.document_access } : {}),
      },
      { onConflict: "company_id" }
    )
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("security_settings_update_failed");
  }

  await createAuditLog(context, {
    moduleKey: "administration",
    entityType: "security_settings",
    entityId: context.profile.company_id ?? undefined,
    action: "updated_security_settings",
    afterValue: data as Record<string, unknown>,
  });

  return data;
}

function ensureRole(profile: AuthUserProfile, allowedRoles: AppRole[]) {
  if (!allowedRoles.includes(profile.role)) {
    throw new Error("forbidden");
  }
}

export async function listLoginSessions() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  const { data, error } = await context.admin
    .from("login_sessions")
    .select("*")
    .eq("company_id", context.profile.company_id)
    .order("created_at", { ascending: false })
    .limit(200);

  if (error) {
    throw error;
  }
  return data ?? [];
}

export async function listAccessLogs() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  const { data, error } = await context.admin
    .from("access_logs")
    .select("*")
    .eq("company_id", context.profile.company_id)
    .order("created_at", { ascending: false })
    .limit(200);

  if (error) {
    throw error;
  }

  return data ?? [];
}

export async function listAuditOversight() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  const { data, error } = await context.admin
    .from("audit_logs")
    .select("*")
    .eq("company_id", context.profile.company_id)
    .order("created_at", { ascending: false })
    .limit(200);

  if (error) {
    throw error;
  }

  return data ?? [];
}

export async function getSystemHealth() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);
  const admin = createSupabaseAdminClient();
  const companyId = context.profile.company_id;
  const isPlatformOwner = context.profile.role === "Super Admin";

  const authCheck = await admin.auth.admin.listUsers({ page: 1, perPage: 1 });
  const databaseCheck = await context.admin.from("companies").select("id").limit(1);
  const buckets = getStorageBucketNames();
  const environment = getAppEnvironment();

  const storageChecks = await Promise.all(
    Object.values(buckets).map(async (bucket) => {
      try {
        const result = await admin.storage.from(bucket).list("", { limit: 1 });
        return {
          bucket,
          status: result.error ? "error" : "ok",
          detail: result.error?.message ?? "reachable",
        };
      } catch (error) {
        return {
          bucket,
          status: "error",
          detail: error instanceof Error ? error.message : "storage_check_failed",
        };
      }
    })
  );

  let loginFailuresQuery = context.admin
    .from("login_sessions")
    .select("id", { count: "exact", head: true })
    .in("status", ["failed", "blocked"]);
  let recentFailuresQuery = context.admin
    .from("login_sessions")
    .select("email, role, status, action, created_at")
    .in("status", ["failed", "blocked"])
    .order("created_at", { ascending: false })
    .limit(6);
  let pendingApprovalsQuery = context.admin
    .from("approval_tasks")
    .select("id", { count: "exact", head: true })
    .eq("status", "pending");
  let payrollRunsQuery = context.admin
    .from("payroll_runs")
    .select("id, status, processed_at, created_at", { count: "exact" })
    .order("created_at", { ascending: false })
    .limit(12);
  let payrollExportFailuresQuery = context.admin
    .from("payroll_exports")
    .select("id, export_type, status, created_at, file_name", { count: "exact" })
    .eq("status", "failed")
    .order("created_at", { ascending: false })
    .limit(8);
  let payrollExportSuccessQuery = context.admin
    .from("payroll_exports")
    .select("id", { count: "exact", head: true });
  let reportExportsQuery = context.admin
    .from("report_exports")
    .select("id", { count: "exact", head: true });
  let activeTenantsQuery = context.admin
    .from("companies")
    .select("id", { count: "exact", head: true })
    .eq("status", "active");
  let employeeHealthRowsQuery = context.admin
    .from("employees")
    .select("id, kra_pin, shif_number, nssf_number, bank_name, bank_account")
    .limit(2500);

  if (companyId) {
    loginFailuresQuery = loginFailuresQuery.eq("company_id", companyId);
    recentFailuresQuery = recentFailuresQuery.eq("company_id", companyId);
    pendingApprovalsQuery = pendingApprovalsQuery.eq("company_id", companyId);
    payrollRunsQuery = payrollRunsQuery.eq("company_id", companyId);
    payrollExportFailuresQuery = payrollExportFailuresQuery.eq("company_id", companyId);
    payrollExportSuccessQuery = payrollExportSuccessQuery.eq("company_id", companyId);
    reportExportsQuery = reportExportsQuery.eq("company_id", companyId);
    employeeHealthRowsQuery = employeeHealthRowsQuery.eq("company_id", companyId);
  }

  const [
    loginFailuresResult,
    recentFailuresResult,
    pendingApprovalsResult,
    payrollRunsResult,
    payrollExportFailuresResult,
    payrollExportSuccessResult,
    reportExportsResult,
    activeTenantsResult,
    employeeHealthRowsResult,
  ] = await Promise.all([
    loginFailuresQuery,
    recentFailuresQuery,
    pendingApprovalsQuery,
    payrollRunsQuery,
    payrollExportFailuresQuery,
    payrollExportSuccessQuery,
    reportExportsQuery,
    activeTenantsQuery,
    employeeHealthRowsQuery,
  ]);

  const employeeHealthRows = (employeeHealthRowsResult.data ?? []) as Array<Record<string, unknown>>;
  const missingKraPins = employeeHealthRows.filter((row) => !safeString(row.kra_pin)).length;
  const missingShifNumbers = employeeHealthRows.filter((row) => !safeString(row.shif_number)).length;
  const missingNssfNumbers = employeeHealthRows.filter((row) => !safeString(row.nssf_number)).length;
  const missingBankDetails = employeeHealthRows.filter(
    (row) => !safeString(row.bank_name) || !safeString(row.bank_account)
  ).length;
  const failedExports = payrollExportFailuresResult.count ?? 0;
  const totalPayrollExports = payrollExportSuccessResult.count ?? 0;
  const reportExports = reportExportsResult.count ?? 0;
  const exportSuccessRate =
    totalPayrollExports > 0
      ? Math.max(0, Math.round(((totalPayrollExports - failedExports) / totalPayrollExports) * 100))
      : 100;
  const payrollRuns = ((payrollRunsResult.data ?? []) as Array<Record<string, unknown>>) ?? [];
  const pendingApprovals = pendingApprovalsResult.count ?? 0;
  const loginFailures = loginFailuresResult.count ?? 0;
  const unhealthyServices = [
    authCheck.error ? "Supabase Auth" : "",
    databaseCheck.error ? "Primary database" : "",
    ...storageChecks.filter((item) => item.status === "error").map((item) => `Storage: ${item.bucket}`),
  ].filter(Boolean);
  const healthScore = Math.max(
    35,
    100 -
      failedExports * 5 -
      Math.min(25, pendingApprovals * 2) -
      Math.min(20, loginFailures * 2) -
      Math.min(20, missingBankDetails + missingKraPins)
  );

  return {
    summaryCards: [
      {
        label: isPlatformOwner ? "Active tenants" : "Tenant scope",
        value: String(isPlatformOwner ? activeTenantsResult.count ?? 0 : 1),
        hint: isPlatformOwner ? "Organizations currently active on Solva HR" : "Current organization context",
      },
      {
        label: "Export success rate",
        value: `${exportSuccessRate}%`,
        hint: `${Math.max(0, totalPayrollExports - failedExports)} successful of ${totalPayrollExports} payroll exports`,
      },
      {
        label: "Payroll runs tracked",
        value: String(payrollRunsResult.count ?? payrollRuns.length),
        hint: "Recent payroll activity captured in production logs",
      },
      {
        label: "Pending approvals",
        value: String(pendingApprovals),
        hint: "Outstanding workflow queue items",
      },
      {
        label: "Login failures",
        value: String(loginFailures),
        hint: "Failed or blocked sign-in attempts in current scope",
      },
      {
        label: "Operational health score",
        value: `${healthScore}/100`,
        hint: unhealthyServices.length ? "Action recommended" : "Healthy production posture",
      },
    ],
    auth: {
      status: authCheck.error ? "error" : "ok",
      detail: authCheck.error?.message ?? "Supabase auth admin reachable",
    },
    database: {
      status: databaseCheck.error ? "error" : "ok",
      detail: databaseCheck.error?.message ?? "Database queries healthy",
    },
    storage: storageChecks,
    build: {
      appVersion: process.env.VERCEL_GIT_COMMIT_SHA ?? "local-build",
      environment,
      runtime: process.env.VERCEL_REGION ?? "local-node",
    },
    operations: {
      pendingApprovals,
      reportExports,
      failedPayrollExports: failedExports,
      recentPayrollStatuses: payrollRuns.map((row) => ({
        status: safeString(row.status, "unknown"),
        processedAt: safeString(row.processed_at, safeString(row.created_at)),
      })),
      recentFailures: [
        ...((recentFailuresResult.data ?? []) as Array<Record<string, unknown>>).map((row) => ({
          source: "auth",
          title: `${safeString(row.email, "Unknown user")} ${safeString(row.status, "failed")}`,
          detail: `${safeString(row.role, "Unknown role")} | ${safeString(row.action, "login_attempt")}`,
          occurredAt: safeString(row.created_at),
        })),
        ...((payrollExportFailuresResult.data ?? []) as Array<Record<string, unknown>>).map((row) => ({
          source: "payroll_export",
          title: safeString(row.export_type, "Payroll export failure"),
          detail: safeString(row.file_name, "File was not produced"),
          occurredAt: safeString(row.created_at),
        })),
      ].slice(0, 10),
    },
    dataQuality: {
      missingKraPins,
      missingShifNumbers,
      missingNssfNumbers,
      missingBankDetails,
    },
    compliance: {
      payrollHistory: "Immutable after close with reopen audit trail",
      auditExport: "Available through audit oversight and export logs",
      retentionPolicies: [
        "Payslips retained for at least 7 years",
        "Payroll reports retained for at least 7 years",
        "Audit logs retained until archive policy is formally activated",
        "Employee master record history preserved through audit trail updates",
      ],
    },
    supportReadiness: {
      unhealthyServices,
      supportActions: [
        "Inspect failed payroll exports",
        "Review suspicious login attempts",
        "Force sign-out compromised users",
        "Resend onboarding access where needed",
        "Check missing employee compliance data",
      ],
      alertPlaceholders: [
        "Payroll export failure alert placeholder",
        "Repeated login failure alert placeholder",
        "Storage quota warning placeholder",
      ],
    },
    environmentSeparation: {
      development: "Local workstation and seeded sandbox data",
      staging: "Preview / staging deployments use isolated environment variables",
      production: "Stable tenant-facing deployment and storage paths",
    },
    placeholders: [
      "Background job monitor will deepen once automated queues are wired",
      "Third-party alert routing is still a placeholder for email/Slack escalation",
    ],
  };
}

export async function getSupportConsole() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  const companyId = context.profile.company_id;
  let failedExportsQuery = context.admin
    .from("payroll_exports")
    .select("id, export_type, file_name, created_at, status", { count: "exact" })
    .eq("status", "failed")
    .order("created_at", { ascending: false })
    .limit(10);
  let failedAuthQuery = context.admin
    .from("login_sessions")
    .select("email, role, status, ip_address, created_at", { count: "exact" })
    .in("status", ["failed", "blocked"])
    .order("created_at", { ascending: false })
    .limit(10);
  let activeSessionsQuery = context.admin
    .from("login_sessions")
    .select("email, role, status, active, created_at")
    .eq("active", true)
    .order("created_at", { ascending: false })
    .limit(10);
  let approvalsQuery = context.admin
    .from("approval_tasks")
    .select("id", { count: "exact", head: true })
    .eq("status", "pending");
  let employeeRowsQuery = context.admin
    .from("employees")
    .select("id, kra_pin, shif_number, nssf_number, bank_name, bank_account")
    .limit(2500);
  let auditQuery = context.admin
    .from("audit_logs")
    .select("module_key, action, created_at, entity_type")
    .order("created_at", { ascending: false })
    .limit(12);

  if (companyId) {
    failedExportsQuery = failedExportsQuery.eq("company_id", companyId);
    failedAuthQuery = failedAuthQuery.eq("company_id", companyId);
    activeSessionsQuery = activeSessionsQuery.eq("company_id", companyId);
    approvalsQuery = approvalsQuery.eq("company_id", companyId);
    employeeRowsQuery = employeeRowsQuery.eq("company_id", companyId);
    auditQuery = auditQuery.eq("company_id", companyId);
  }

  const [failedExportsResult, failedAuthResult, activeSessionsResult, approvalsResult, employeeRowsResult, auditResult] =
    await Promise.all([
      failedExportsQuery,
      failedAuthQuery,
      activeSessionsQuery,
      approvalsQuery,
      employeeRowsQuery,
      auditQuery,
    ]);

  const employeeRows = (employeeRowsResult.data ?? []) as Array<Record<string, unknown>>;
  const missingData = {
    missingKraPins: employeeRows.filter((row) => !safeString(row.kra_pin)).length,
    missingShifNumbers: employeeRows.filter((row) => !safeString(row.shif_number)).length,
    missingNssfNumbers: employeeRows.filter((row) => !safeString(row.nssf_number)).length,
    missingBankDetails: employeeRows.filter(
      (row) => !safeString(row.bank_name) || !safeString(row.bank_account)
    ).length,
  };
  const unresolvedWarnings =
    missingData.missingKraPins +
    missingData.missingShifNumbers +
    missingData.missingNssfNumbers +
    missingData.missingBankDetails;
  const healthScore = Math.max(
    40,
    100 -
      (failedExportsResult.count ?? 0) * 6 -
      (failedAuthResult.count ?? 0) * 2 -
      (approvalsResult.count ?? 0) * 2 -
      Math.min(30, unresolvedWarnings)
  );

  return {
    cards: [
      { label: "Tenant health score", value: `${healthScore}/100`, hint: "Composite support signal for this organization" },
      { label: "Failed payroll exports", value: String(failedExportsResult.count ?? 0), hint: "Recent failures needing support follow-up" },
      { label: "Failed sign-ins", value: String(failedAuthResult.count ?? 0), hint: "Potential security or onboarding friction" },
      { label: "Pending approvals", value: String(approvalsResult.count ?? 0), hint: "Backlog that may delay payroll and HR operations" },
      { label: "Active sessions", value: String((activeSessionsResult.data ?? []).length), hint: "Current signed-in users in this workspace" },
      { label: "Missing compliance data", value: String(unresolvedWarnings), hint: "Employee filing gaps still requiring cleanup" },
    ],
    failedExports: (failedExportsResult.data ?? []) as Array<Record<string, unknown>>,
    riskyAccounts: ((failedAuthResult.data ?? []) as Array<Record<string, unknown>>).map((row) => ({
      email: safeString(row.email),
      role: safeString(row.role),
      status: safeString(row.status),
      ip: safeString(row.ip_address, "-"),
      created_at: safeString(row.created_at),
    })),
    activeSessions: (activeSessionsResult.data ?? []) as Array<Record<string, unknown>>,
    dataQuality: [
      { title: "Missing KRA PIN", value: missingData.missingKraPins, detail: "Blocks or weakens PAYE and P9 readiness" },
      { title: "Missing SHIF number", value: missingData.missingShifNumbers, detail: "Rows can still export with warnings where template allows" },
      { title: "Missing NSSF number", value: missingData.missingNssfNumbers, detail: "Needs cleanup for clean NSSF submissions" },
      { title: "Missing bank details", value: missingData.missingBankDetails, detail: "Net to Bank rows are excluded until fixed" },
    ],
    recommendedActions: [
      "Force sign-out compromised accounts from User Management when repeated failures are suspicious.",
      "Use Audit Oversight to inspect payroll state changes before reopening or closing a period.",
      "Review failed payroll exports before rerunning month-end filing packs.",
      "Prioritize missing employee compliance data before statutory filing deadlines.",
      "Resend onboarding access for invited users who have not activated successfully.",
    ],
    recentAudit: (auditResult.data ?? []) as Array<Record<string, unknown>>,
    safeguards: [
      "Payroll close requires approved status and now respects validation blockers.",
      "Session timeout follows tenant security settings with forced logout on inactivity.",
      "Employer onboarding remains approval-gated before workspace activation.",
    ],
  };
}

function parseCsvContent(content: string) {
  const rows: string[][] = [];
  let current = "";
  let row: string[] = [];
  let insideQuotes = false;

  for (let index = 0; index < content.length; index += 1) {
    const character = content[index];
    const next = content[index + 1];

    if (character === "\"") {
      if (insideQuotes && next === "\"") {
        current += "\"";
        index += 1;
      } else {
        insideQuotes = !insideQuotes;
      }
      continue;
    }

    if (character === "," && !insideQuotes) {
      row.push(current.trim());
      current = "";
      continue;
    }

    if ((character === "\n" || character === "\r") && !insideQuotes) {
      if (character === "\r" && next === "\n") {
        index += 1;
      }
      row.push(current.trim());
      current = "";
      if (row.some((value) => value.length > 0)) {
        rows.push(row);
      }
      row = [];
      continue;
    }

    current += character;
  }

  row.push(current.trim());
  if (row.some((value) => value.length > 0)) {
    rows.push(row);
  }

  const [header = [], ...body] = rows;
  return {
    header,
    body: body.map((values) =>
      Object.fromEntries(header.map((column, columnIndex) => [column, values[columnIndex] ?? ""]))
    ),
  };
}

async function resolveCompanyLookups(context: RequestContext) {
  const [branches, departments] = await Promise.all([
    listCompanyScopedLookup("branches", context.profile.company_id),
    listCompanyScopedLookup("departments", context.profile.company_id),
  ]);

  return {
    branchByCode: new Map(branches.map((branch) => [safeString(branch.code), safeString(branch.id)])),
    departmentByCode: new Map(departments.map((department) => [safeString(department.code), safeString(department.id)])),
  };
}

export async function listDataImportJobs() {
  const context = await getRequestContext();
  ensureAdminAccess(context.profile);

  const { data, error } = await context.admin
    .from("data_import_jobs")
    .select("*")
    .eq("company_id", context.profile.company_id)
    .order("created_at", { ascending: false })
    .limit(50);

  if (error) {
    throw error;
  }

  return data ?? [];
}

export async function runDataImport(input: {
  importType: "employees" | "branches" | "departments" | "designations" | "job_grades" | "payroll_groups";
  fileName: string;
  content: string;
  previewOnly?: boolean;
}) {
  const context = await getRequestContext();
  ensureAdminManageAccess(context.profile);

  const parsed = parseCsvContent(input.content);
  const errors: Array<{ row: number; message: string }> = [];
  let successCount = 0;

  const job = await context.admin
    .from("data_import_jobs")
    .insert({
      company_id: context.profile.company_id,
      import_type: input.importType,
      file_name: input.fileName,
      status: input.previewOnly ? "preview" : "processing",
      row_count: parsed.body.length,
      created_by: context.profile.id,
    })
    .select("*")
    .single();

  if (job.error || !job.data) {
    throw job.error ?? new Error("import_job_create_failed");
  }

  const lookupMaps = await resolveCompanyLookups(context);
  const admin = createSupabaseAdminClient();

  for (const [index, row] of parsed.body.entries()) {
    try {
      if (input.importType === "branches") {
        if (!safeString(row.code) || !safeString(row.name)) {
          throw new Error("Branch import requires code and name.");
        }
        if (!input.previewOnly) {
          await context.admin.from("branches").upsert({
            company_id: context.profile.company_id,
            code: safeString(row.code),
            name: safeString(row.name),
            location: safeString(row.location, null as never),
            contact_email: safeString(row.contact_email, null as never),
            contact_phone: safeString(row.contact_phone, null as never),
            status: safeString(row.status, "active"),
          }, { onConflict: "company_id,code" });
        }
      } else if (input.importType === "departments") {
        if (!safeString(row.code) || !safeString(row.name)) {
          throw new Error("Department import requires code and name.");
        }
        if (!input.previewOnly) {
          await context.admin.from("departments").upsert({
            company_id: context.profile.company_id,
            code: safeString(row.code),
            name: safeString(row.name),
            branch_id: lookupMaps.branchByCode.get(safeString(row.branch_code)) ?? null,
            status: safeString(row.status, "active"),
          }, { onConflict: "company_id,code" });
        }
      } else if (input.importType === "designations") {
        if (!safeString(row.code) || !safeString(row.title)) {
          throw new Error("Designation import requires code and title.");
        }
        if (!input.previewOnly) {
          await context.admin.from("designations").upsert({
            company_id: context.profile.company_id,
            code: safeString(row.code),
            title: safeString(row.title),
            status: safeString(row.status, "active"),
          }, { onConflict: "company_id,code" });
        }
      } else if (input.importType === "job_grades") {
        if (!safeString(row.code) || !safeString(row.name)) {
          throw new Error("Job grade import requires code and name.");
        }
        if (!input.previewOnly) {
          await context.admin.from("job_grades").upsert({
            company_id: context.profile.company_id,
            code: safeString(row.code),
            name: safeString(row.name),
            level_rank: safeNumber(row.level_rank, 1),
            status: safeString(row.status, "active"),
          }, { onConflict: "company_id,code" });
        }
      } else if (input.importType === "payroll_groups") {
        if (!safeString(row.name)) {
          throw new Error("Payroll group import requires name.");
        }
        if (!input.previewOnly) {
          await context.admin.from("payroll_groups").upsert({
            company_id: context.profile.company_id,
            name: safeString(row.name),
            frequency: safeString(row.frequency, "Monthly"),
            currency: safeString(row.currency, "KES"),
            cut_off_day: safeNumber(row.cut_off_day, 25),
            pay_day: safeNumber(row.pay_day, 28),
            status: safeString(row.status, "active"),
          }, { onConflict: "company_id,name" });
        }
      } else if (input.importType === "employees") {
        if (!safeString(row.employee_number) || !safeString(row.first_name) || !safeString(row.last_name)) {
          throw new Error("Employee import requires employee_number, first_name, and last_name.");
        }
        if (!input.previewOnly) {
          await admin.from("employees").upsert({
            company_id: context.profile.company_id,
            employee_number: safeString(row.employee_number),
            first_name: safeString(row.first_name),
            last_name: safeString(row.last_name),
            email: safeString(row.email, `${safeString(row.first_name)}.${safeString(row.last_name)}@solvahr.app`.toLowerCase()),
            phone: safeString(row.phone, "0700000000"),
            employment_type: safeString(row.employment_type, "Permanent"),
            department_id: lookupMaps.departmentByCode.get(safeString(row.department_code)) ?? null,
            branch_id: lookupMaps.branchByCode.get(safeString(row.branch_code)) ?? null,
            status: safeString(row.status, "Active"),
            salary: safeNumber(row.salary, 0),
          }, { onConflict: "employee_number" });
        }
      }

      successCount += 1;
    } catch (error) {
      errors.push({
        row: index + 2,
        message: error instanceof Error ? error.message : "Import row failed.",
      });
    }
  }

  const { data, error } = await context.admin
    .from("data_import_jobs")
    .update({
      status: input.previewOnly ? "preview" : errors.length > 0 ? "partial" : "completed",
      success_count: successCount,
      failure_count: errors.length,
      error_summary: errors,
    })
    .eq("id", safeString(job.data.id))
    .select("*")
    .single();

  if (error || !data) {
    throw error ?? new Error("import_job_update_failed");
  }

  await createAuditLog(context, {
    moduleKey: "administration",
    entityType: "data_import_job",
    entityId: safeString(data.id),
    action: input.previewOnly ? "previewed_data_import" : "executed_data_import",
    afterValue: data as Record<string, unknown>,
  });

  return data;
}

