// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/book-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book-demo">> = Specific
  const handler = {} as typeof import("../../src/app/book-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact-sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact-sales">> = Specific
  const handler = {} as typeof import("../../src/app/contact-sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cv-service-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cv-service-admin">> = Specific
  const handler = {} as typeof import("../../src/app/cv-service-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cv-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cv-service">> = Specific
  const handler = {} as typeof import("../../src/app/cv-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features">> = Specific
  const handler = {} as typeof import("../../src/app/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forbidden/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forbidden">> = Specific
  const handler = {} as typeof import("../../src/app/forbidden/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guided-setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guided-setup">> = Specific
  const handler = {} as typeof import("../../src/app/guided-setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hr-modules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr-modules">> = Specific
  const handler = {} as typeof import("../../src/app/hr-modules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/insights">> = Specific
  const handler = {} as typeof import("../../src/app/insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/leave/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leave/new">> = Specific
  const handler = {} as typeof import("../../src/app/leave/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll">> = Specific
  const handler = {} as typeof import("../../src/app/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payroll/periods/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll/periods/new">> = Specific
  const handler = {} as typeof import("../../src/app/payroll/periods/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pending-approval/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pending-approval">> = Specific
  const handler = {} as typeof import("../../src/app/pending-approval/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/people/employees/[employeeId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/people/employees/[employeeId]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/people/employees/[employeeId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/people/employees/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/people/employees/new">> = Specific
  const handler = {} as typeof import("../../src/app/people/employees/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/performance/appraisals/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/appraisals/new">> = Specific
  const handler = {} as typeof import("../../src/app/performance/appraisals/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security">> = Specific
  const handler = {} as typeof import("../../src/app/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/start-free-trial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/start-free-trial">> = Specific
  const handler = {} as typeof import("../../src/app/start-free-trial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools">> = Specific
  const handler = {} as typeof import("../../src/app/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/unauthorized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unauthorized">> = Specific
  const handler = {} as typeof import("../../src/app/unauthorized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/.well-known/[...slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/.well-known/[...slug]">> = Specific
  const handler = {} as typeof import("../../src/app/.well-known/[...slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/access-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/access-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/access-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/approval-workflows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/approval-workflows">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/approval-workflows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/audit-oversight/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit-oversight">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/audit-oversight/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/billing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/billing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/company-branding/logo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/company-branding/logo">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/company-branding/logo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/company-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/company-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/company-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/cv-service/cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cv-service/cleanup">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/cv-service/cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/cv-service/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cv-service/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/cv-service/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/cv-service/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cv-service/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/cv-service/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/cv-service/orders/[orderId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cv-service/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/cv-service/orders/[orderId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/employer-registrations/[companyId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/employer-registrations/[companyId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/employer-registrations/[companyId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/imports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/imports">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/imports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/login-sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login-sessions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/login-sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/notification-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/notification-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/notification-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/permissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reference-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reference-data">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reference-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/roles/[roleKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/roles/[roleKey]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/roles/[roleKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/roles">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/saas-hq/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/saas-hq">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/saas-hq/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/security-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/security-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/security-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/support-console/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/support-console">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/support-console/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/system-health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system-health">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/system-health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[userId]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[userId]/actions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[userId]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[userId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/assistant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/assistant">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/assistant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/approval-tasks/[taskId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/approval-tasks/[taskId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/approval-tasks/[taskId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/approval-tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/approval-tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/approval-tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/[assetId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/[assetId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/[assetId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/workspace">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance/overtime/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/overtime">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance/overtime/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance/records/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/records">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance/records/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/employer-signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/employer-signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/employer-signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/consultancy/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consultancy/workspace">> = Specific
  const handler = {} as typeof import("../../src/app/api/consultancy/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/action-messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/action-messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/action-messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/appraisals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/appraisals">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/appraisals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/assets">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/attendance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/attendance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/change-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/company-documents/[documentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/company-documents/[documentId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/company-documents/[documentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/company-documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/company-documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/company-documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/complaints/[complaintId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/complaints/[complaintId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/complaints/[complaintId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/complaints/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/complaints">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/complaints/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/documents/[documentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/documents/[documentId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/documents/[documentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/leave/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/leave">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/leave/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/loans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/loans">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/loans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/notifications/[notificationId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/notifications/[notificationId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/notifications/[notificationId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/p9/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/p9">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/p9/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/payslips/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/payslips">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/payslips/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/profile-photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/profile-photo">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/profile-photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/profile-update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/profile-update">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/profile-update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/salary-advances/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/salary-advances">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/salary-advances/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ess/training/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ess/training">> = Specific
  const handler = {} as typeof import("../../src/app/api/ess/training/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/workspace">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/adjustments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/adjustments">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/adjustments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/approval-queue/[taskId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/approval-queue/[taskId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/approval-queue/[taskId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/approval-queue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/approval-queue">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/approval-queue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/attendance-dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/attendance-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/attendance-dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/balances/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/balances">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/balances/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/daily-attendance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/daily-attendance">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/daily-attendance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/devices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/devices">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/devices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/forms/[requestId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/forms/[requestId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/forms/[requestId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/holidays/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/holidays">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/holidays/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/lateness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/lateness">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/lateness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/overtime/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/overtime">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/overtime/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/policies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/policies">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/policies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/requests/[requestId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/requests/[requestId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/requests/[requestId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/shifts/assignments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/shifts/assignments">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/shifts/assignments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/shifts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/shifts">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/shifts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/shifts/template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/shifts/template">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/shifts/template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/shifts/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/shifts/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/shifts/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/shifts/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/shifts/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/shifts/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/timesheets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/timesheets">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/timesheets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave/weekend-rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave/weekend-rules">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave/weekend-rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/lookups/[table]/[recordId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lookups/[table]/[recordId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/lookups/[table]/[recordId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/lookups/[table]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lookups/[table]">> = Specific
  const handler = {} as typeof import("../../src/app/api/lookups/[table]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mcp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp">> = Specific
  const handler = {} as typeof import("../../src/app/api/mcp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/modules/[moduleKey]/pages/[pageKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/modules/[moduleKey]/pages/[pageKey]">> = Specific
  const handler = {} as typeof import("../../src/app/api/modules/[moduleKey]/pages/[pageKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/modules/[moduleKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/modules/[moduleKey]">> = Specific
  const handler = {} as typeof import("../../src/app/api/modules/[moduleKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/additions/[additionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/additions/[additionId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/additions/[additionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/additions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/additions">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/additions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/audit-trail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/audit-trail">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/audit-trail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/day-deductions/[deductionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/day-deductions/[deductionId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/day-deductions/[deductionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/day-deductions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/day-deductions">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/day-deductions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/employee-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/employee-data">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/employee-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/exports/[exportType]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/exports/[exportType]">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/exports/[exportType]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/exports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/exports">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/exports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/package/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/package">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/package/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/payslips/[employeeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/payslips/[employeeId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/payslips/[employeeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/payslips/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/payslips/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/payslips/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/payslips/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/payslips">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/payslips/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/periods/[periodId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/periods/[periodId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/periods/[periodId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/periods/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/periods">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/periods/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/process">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/review">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payroll/statutory-reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payroll/statutory-reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/payroll/statutory-reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/people/employees/[employeeId]/action-messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/people/employees/[employeeId]/action-messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/people/employees/[employeeId]/action-messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/people/employees/[employeeId]/documents/[documentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/people/employees/[employeeId]/documents/[documentId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/people/employees/[employeeId]/documents/[documentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/people/employees/[employeeId]/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/people/employees/[employeeId]/documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/people/employees/[employeeId]/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/people/employees/[employeeId]/hr-documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/people/employees/[employeeId]/hr-documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/people/employees/[employeeId]/hr-documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/people/employees/[employeeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/people/employees/[employeeId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/people/employees/[employeeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/people/employees/[employeeId]/user-account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/people/employees/[employeeId]/user-account">> = Specific
  const handler = {} as typeof import("../../src/app/api/people/employees/[employeeId]/user-account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/people/employees/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/people/employees/requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/people/employees/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/people/employees/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/people/employees">> = Specific
  const handler = {} as typeof import("../../src/app/api/people/employees/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/people/employees/user-accounts/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/people/employees/user-accounts/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/people/employees/user-accounts/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/cycles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/cycles">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/cycles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/goals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/goals">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/goals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/kpis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/kpis">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/kpis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/pips/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/pips">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/pips/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/promotion-cases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/promotion-cases">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/promotion-cases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/reports/[reviewId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/reports/[reviewId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/reports/[reviewId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/reviews/[reviewId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/reviews/[reviewId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/reviews/[reviewId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/salary-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/salary-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/salary-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/succession/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/succession">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/succession/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/talent-matrix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/talent-matrix">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/talent-matrix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/work-plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/work-plans">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/work-plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/performance/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance/workspace">> = Specific
  const handler = {} as typeof import("../../src/app/api/performance/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/platform/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform">> = Specific
  const handler = {} as typeof import("../../src/app/api/platform/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/cv-service/orders/[orderId]/downloads/[format]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/cv-service/orders/[orderId]/downloads/[format]">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/cv-service/orders/[orderId]/downloads/[format]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/cv-service/orders/[orderId]/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/cv-service/orders/[orderId]/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/cv-service/orders/[orderId]/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/cv-service/orders/[orderId]/payment-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/cv-service/orders/[orderId]/payment-test">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/cv-service/orders/[orderId]/payment-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/cv-service/orders/[orderId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/cv-service/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/cv-service/orders/[orderId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/cv-service/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/cv-service/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/cv-service/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/cv-service/uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/cv-service/uploads">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/cv-service/uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/leads">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/plans">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/workspace">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/referrals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referrals">> = Specific
  const handler = {} as typeof import("../../src/app/api/referrals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/access-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/access-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/access-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/builder/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/builder/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/builder/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/category/[categoryKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/category/[categoryKey]">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/category/[categoryKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/exports/[exportId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/exports/[exportId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/exports/[exportId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/exports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/exports">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/exports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/saved/[reportId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/saved/[reportId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/saved/[reportId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/saved/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/saved">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/saved/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/scheduled/[scheduleId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/scheduled/[scheduleId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/scheduled/[scheduleId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/scheduled/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/scheduled">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/scheduled/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/training/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training/workspace">> = Specific
  const handler = {} as typeof import("../../src/app/api/training/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
