var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/cv-service-admin/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bc0mqb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0qf8._h.js")
R.c("server/chunks/ssr/_1149faf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lxb38_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/src_0deov.j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_cv-service-admin_page_actions_0usmo8v.js")
R.m(4423)
module.exports=R.m(4423).exports
