services:
  - type: web
    name: solva-hris-api-staging
    runtime: node
    plan: free
    region: oregon
    branch: main
    autoDeployTrigger: commit
    buildCommand: npm install && npm run build --workspace @solva/shared && npm run build --workspace @solva/api
    startCommand: npm run start --workspace @solva/api
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 22.15.0
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://shjjeushhoeaniiwtzup.supabase.co
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true

  - type: web
    name: solva-hris-web-staging
    runtime: node
    plan: free
    region: oregon
    branch: main
    autoDeployTrigger: commit
    buildCommand: npm install && npm run build --workspace @solva/shared && npm run build --workspace @solva/web
    startCommand: npm run start --workspace @solva/web
    envVars:
      - key: NODE_VERSION
        value: 22.15.0
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://solva-hris-api-staging.onrender.com
      - key: API_INTERNAL_HOSTPORT
        fromService:
          type: web
          name: solva-hris-api-staging
          property: hostport
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://shjjeushhoeaniiwtzup.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
        sync: false
