var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/people/employees/[employeeId]/documents/[documentId]/route.js")
R.c("server/chunks/src_lib_solva-data_ts_0rc~46r._.js")
R.c("server/chunks/[root-of-the-server]__0gdw2ny._.js")
R.c("server/chunks/src_lib_saas_ts_0labvjx._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/src_lib_0o_zyog._.js")
R.c("server/chunks/src_lib_database_ts_103x3zd._.js")
R.c("server/chunks/node_modules_xlsx_xlsx_mjs_0eepc5h._.js")
R.c("server/chunks/_0p6-xjp._.js")
R.c("server/chunks/0ash_api_people_employees_[employeeId]_documents_[documentId]_route_actions_0l3vbic.js")
R.m(77184)
module.exports=R.m(77184).exports
