var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/saas-hq/route.js")
R.c("server/chunks/[root-of-the-server]__01mqfrt._.js")
R.c("server/chunks/_0p6-xjp._.js")
R.c("server/chunks/src_lib_saas_ts_0labvjx._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_saas-hq_route_actions_07dzb2c.js")
R.m(71001)
module.exports=R.m(71001).exports
