var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/leave/new/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__10wda5c._.js")
R.c("server/chunks/ssr/_0s-xveh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/_1149faf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0g3yr8a.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lxb38_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/src_0deov.j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_leave_new_page_actions_06-6hnn.js")
R.m(14959)
module.exports=R.m(14959).exports
