var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/pending-approval/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c-a.ll._.js")
R.c("server/chunks/ssr/_0s-xveh._.js")
R.c("server/chunks/ssr/_1149faf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_06j~hhm.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lxb38_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/src_0deov.j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_pending-approval_page_actions_0.90d.4.js")
R.m(91269)
module.exports=R.m(91269).exports
