var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/tools/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__05bse4s._.js")
R.c("server/chunks/ssr/src_lib_saas_ts_0cklfl2._.js")
R.c("server/chunks/ssr/_05syjj9._.js")
R.c("server/chunks/ssr/_0qe~6-8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0g3o26x.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lxb38_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/src_0deov.j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_tools_page_actions_0aaw_r4.js")
R.m(6060)
module.exports=R.m(6060).exports
