var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/leave/holidays/route.js")
R.c("server/chunks/[root-of-the-server]__0h0_9hh._.js")
R.c("server/chunks/src_lib_solva-data_ts_0rc~46r._.js")
R.c("server/chunks/src_lib_saas_ts_0labvjx._.js")
R.c("server/chunks/src_lib_0o_zyog._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/src_lib_database_ts_103x3zd._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/node_modules_xlsx_xlsx_mjs_0eepc5h._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/_0p6-xjp._.js")
R.c("server/chunks/_next-internal_server_app_api_leave_holidays_route_actions_02kjk42.js")
R.m(22572)
module.exports=R.m(22572).exports
