var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ess/appraisals/route.js")
R.c("server/chunks/[root-of-the-server]__08b-l8e._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/src_lib_performance-management_ts_0ahgla2._.js")
R.c("server/chunks/_0p6-xjp._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/node_modules_xlsx_xlsx_mjs_0eepc5h._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/src_lib_04uya_l._.js")
R.c("server/chunks/_next-internal_server_app_api_ess_appraisals_route_actions_07pvn-x.js")
R.m(2516)
module.exports=R.m(2516).exports
