var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/onboarding/route.js")
R.c("server/chunks/[root-of-the-server]__12o10sd._.js")
R.c("server/chunks/_0p6-xjp._.js")
R.c("server/chunks/src_lib_saas_ts_0labvjx._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_onboarding_route_actions_0vqxn03.js")
R.m(66669)
module.exports=R.m(66669).exports
