var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/payroll/page.js")
R.c("server/chunks/ssr/_05syjj9._.js")
R.c("server/chunks/ssr/src_lib_saas_ts_0cklfl2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j5m2d7._.js")
R.c("server/chunks/ssr/_1149faf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0vuf66x.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lxb38_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/src_0deov.j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_payroll_page_actions_0b9.l~u.js")
R.m(52214)
module.exports=R.m(52214).exports
