var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/forgot-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__10k5m7-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0p_8o68.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lxb38_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0t9q526._.js")
R.c("server/chunks/ssr/src_0deov.j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_forgot-password_page_actions_13i8n7b.js")
R.m(72058)
module.exports=R.m(72058).exports
