var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/cv-service/dashboard/route.js")
R.c("server/chunks/[root-of-the-server]__0m_ny~w._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/_0p6-xjp._.js")
R.c("server/chunks/node_modules_pako_0gctttk._.js")
R.c("server/chunks/_0bc78jt._.js")
R.c("server/chunks/node_modules_xlsx_xlsx_mjs_0eepc5h._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_cv-service_dashboard_route_actions_12wrzhx.js")
R.m(62704)
module.exports=R.m(62704).exports
